apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresnaut.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/prometheus"
  labels:
    {{- include "postgresnaut.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "postgresnaut.selectorLabels" . | nindent 4 }}
