apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: jaeger
    labels:
      helm.sh/chart: {{ include "postgresnaut.chart" .  }}
      app.kubernetes.io/instance: {{ .Release.Name  }}
      app.kubernetes.io/managed-by: {{ .Release.Service  }}
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jaeger
    template:
      metadata:
        labels:
          app: jaeger
          app.kubernetes.io/name: jaeger
          app.kubernetes.io/component: all-in-one
          app.kubernetes.io/instance: {{ .Release.Name  }}
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "16686"
      spec:
          containers:
            - image: jaegertracing/all-in-one
              name: jaeger
              ports:
                - containerPort: 5775
                  protocol: UDP
                - containerPort: 6831
                  protocol: UDP
                - containerPort: 6832
                  protocol: UDP
                - containerPort: 5778
                  protocol: TCP
                - containerPort: 16686
                  protocol: TCP
                - containerPort: 9411
                  protocol: TCP
              env:
               - name: COLLECTOR_ZIPKIN_HTTP_PORT
                 value: "9411"
              readinessProbe:
                httpGet:
                  path: "/"
                  port: 14269
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-query
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: query
      helm.sh/chart: {{ include "postgresnaut.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  spec:
    ports:
      - name: query-http
        port: 80
        protocol: TCP
        targetPort: 16686
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: {{ .Release.Name  }}
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-collector
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: collector
      helm.sh/chart: {{ include "postgresnaut.chart" .  }}
      app.kubernetes.io/instance: {{ .Release.Name  }}
      app.kubernetes.io/managed-by: {{ .Release.Service  }}
  spec:
    ports:
    - name: jaeger-collector-tchannel
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: {{ .Release.Name  }}
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-agent
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: agent
      helm.sh/chart: {{ include "postgresnaut.chart" .  }}
      app.kubernetes.io/instance: {{ .Release.Name  }}
      app.kubernetes.io/managed-by: {{ .Release.Service  }}
  spec:
    ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: agent-configs
      port: 5778
      protocol: TCP
      targetPort: 5778
    clusterIP: None
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: {{ .Release.Name  }}
- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin
    labels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: zipkin
      helm.sh/chart: {{ include "postgresnaut.chart" .  }}
      app.kubernetes.io/instance: {{ .Release.Name  }}
      app.kubernetes.io/managed-by: {{ .Release.Service  }}
  spec:
    ports:
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    clusterIP: None
    selector:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: {{ .Release.Name  }}