micronaut:
  application:
    name: postgresnaut
  metrics:
    enabled: true
    binders:
      jvm:
        enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**

    versioning:
      enabled: true
      default-version: 1
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'

flyway:
  datasources:
    default:
      enabled: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgresnaut
    driverClassName: org.postgresql.Driver
    username: dekstroza
    password: dekstroza

jackson:
  bean-introspection-module: true

tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1
    reporter:
      flushInterval: 2000
      maxQueueSize: 200

endpoints:
  prometheus:
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  info:
    enabled: true
    sensitive: false
  health:
    sensitive: false
    enabled: true
    details-visible: ANONYMOUS

